In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv('F1Drivers_Dataset.csv')

In [5]:
#Menunjukan list data 1-5 pertama
df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1960,0.0,0.000000,0.0,0.0,0.0,0.000000,2,False
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1950,0.0,1.000000,0.0,0.0,0.0,0.000000,2,False
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,0.300000,0.0,0.0,0.0,0.000000,2,False
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,NaN,1970,0.0,0.833333,0.0,0.0,0.0,0.166667,5,False
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1990,0.0,1.000000,0.0,0.0,0.0,0.000000,1,False

In [7]:
#negara paling banyak menjadi pembalap F1
NegaraDriver = df['Nationality'].value_counts()
NegaraDriver.head(10)

Nationality
United Kingdom    164
United States     160
Italy              99
France             72
West Germany       39
Brazil             32
Argentina          25
Switzerland        24
Belgium            23
South Africa       23
Name: count, dtype: int64

In [9]:
#menunjukan driver dengan kemenangan / championships terbanyak
DriverChamp = df.loc[df['Championships'].idxmax()]
DriverChamp.head()

Driver                                              Lewis Hamilton
Nationality                                         United Kingdom
Seasons          [2007, 2008, 2009, 2010, 2011, 2012, 2013, 201...
Championships                                                  7.0
Race_Entries                                                 311.0
Name: 338, dtype: object